name: Create static assets
on:
  release:
    types: [published, edited]
  push:
    branches:
      - 'test_gh_actions'
jobs:
  static-assets:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.ref_name}}
      - name: Checkout branch @${{github.ref_name}}
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download requirements
        run: |
          pip install -r requirements.txt
          cp .env.example .env
      - name: Run collectstatic
        run: |
          mkdir static/
          python manage.py collectstatic
        env:
          MODE: PRODUCTION
      - name: Create artifact
        run: zip -r mathesar-v${{github.ref_name}}.zip . -x '*.git*'
      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: mathesar-v${{github.ref_name}}.zip
