# Since we're using both the "require pull request" and "require merge queue"
# requirements for develop and master branches, there's no reason to run tests
# on every push. Instead, we're using the recommended "merge_group" formulation
# that runs status checks and reports them whenever a PR is added to the merge
# queue.

name: Run Python tests
on:  [pull_request, merge_group]
jobs:
  python_filechanges:
    runs-on: ubuntu-latest
    # Here, we capture whether any files have changed to indicate we need to run
    # python tests
    outputs:
      any_changed: ${{ steps.changed_files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            *.py
            mathesar/**
            db/**
  python_tests:
    runs-on: ubuntu-latest
    needs: python_filechanges
    strategy:
      matrix:
        pg-version: [13, 14, 15]
    steps:
      - uses: actions/checkout@v2
      - name: Copy env file
        if: needs.python_filechanges.outputs.any_changed == 'true'
        run: cp .env.example .env
      # The code is checked out under uid 1001 - reset this to 1000 for the
      # container to run tests successfully
      - name: Fix permissions
        if: needs.python_filechanges.outputs.any_changed == 'true'
        run: sudo chown -R 1000:1000 .
      - name: Build the stack
        if: needs.python_filechanges.outputs.any_changed == 'true'
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d test-service
        env:
          PG_MAJOR: ${{ matrix.pg-version }}
      - name: Run tests with pytest
        if: needs.python_filechanges.outputs.any_changed == 'true'
        run: docker exec mathesar_service_test ./run_pytest.sh
  tests:
    runs-on: ubuntu-latest
    needs: python_tests
    steps:
      - name: Report success
        run: echo "Python tests succeeded or skipped!"
